### ISSUE TITLE
[Bug] Switching to old doc versions causes 404

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostatio.github.io#107]
Switching from `2.2.0-latest` to `2.1.0`:

![Screenshot from 2023-04-27 22-33-08](https://user-images.githubusercontent.com/68053619/235040505-f8ad05a8-0364-4548-9480-6b374c1df8aa.png)

The URL seems kinda messed up. This only happens in `Get Started` page.

**Comment by tthvo** [comment]
Also, when we are on an older version of doc, the URL and content is correct but the version selector is still showing `2.2.0-latest`.

![Screenshot from 2023-04-27 22-48-55](https://user-images.githubusercontent.com/68053619/235042588-f39ee327-765d-4e16-8daa-c414012fec32.png)

**Comment by andrewazores** [comment]
Git bisection shows this happened in #76 .
