### ISSUE TITLE
[Bug] Remove documentation of old-style Bearer token auth form

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostatio.github.io#112]
![image](https://github.com/cryostatio/cryostatio.github.io/assets/3787464/b1ca4c83-af92-4573-89bc-ceffa5e820b8)

This authentication method is not implemented anymore and should be removed from documentation. Users deploying in OpenShift will see the OpenShift OAuth redirect flow. Users deployed on other platforms, including any other Kubernetes, will either see no integrated authentication, or will see a Basic auth form (if configured).

**Comment by tthvo** [comment]
Closed?

**Comment by andrewazores** [comment]
Fixed by #113
