### ISSUE TITLE
Getting Started Tutorial Demo App Does Not Work Out Of The Box

### ISSUE THREAD

**Issue by roberttoyonaga** [cryostatio/cryostatio.github.io#114]
The demo app specified [here](https://github.com/cryostatio/cryostatio.github.io/blob/b9eb47b55fc1c80172f0fc4df3787a2aa65ae50e/get-started/index.md?plain=1#L127) doesn't seem to work out of the box. When I tried this tutorial I got a permission denied error. 
![image](https://github.com/cryostatio/cryostatio.github.io/assets/35396843/6c81df08-c94e-443f-a9e9-b31e6ecf0a69)

Unfortunately there was no log output.

Note: I got a similar error when trying to use the quarkus quickstarts (in Java mode) which I resolved by adding chmod 777 to the Dockerfile.

**Comment by andrewazores** [comment]
Could you test it with an updated version of the same sample app, like [here](https://github.com/cryostatio/cryostat-operator/blob/b22cc8b53f0b3666ef3e48d8df8457c1ec78e6c6/Makefile#L427) ?

The sample app [with the Cryostat Agent included](https://github.com/cryostatio/cryostat-operator/blob/b22cc8b53f0b3666ef3e48d8df8457c1ec78e6c6/Makefile#L436) may also be interesting.

**Comment by roberttoyonaga** [comment]
> Could you test it with an updated version of the same sample app, like [here](https://github.com/cryostatio/cryostat-operator/blob/b22cc8b53f0b3666ef3e48d8df8457c1ec78e6c6/Makefile#L427) ?

The newer sample app works great. Looks like just the old version doesn't work. Maybe just the website docs need an update.

**Comment by tthvo** [comment]
Closed?
