### ISSUE TITLE
Upstream docs specify a different min k8s version than OperatorHub

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostatio.github.io#194]
## Upstream docs (1.25+)

![image](https://github.com/cryostatio/cryostatio.github.io/assets/68053619/49260558-9203-4122-acc0-60578ab664ac)

## OperatorHub (1.21+)

![image](https://github.com/cryostatio/cryostatio.github.io/assets/68053619/a460caa6-9301-4cf3-a45c-4b8e0f00bae6)

Cryostat Operator CSV specifies a min k8s version of `1.21` but upstream docs says `1.25`. Just wonder which one is the correct one?

**Comment by andrewazores** [comment]
https://github.com/cryostatio/cryostatio.github.io/pull/184

I believe 1.25 is correct.
