### ISSUE TITLE
Update install instructions with OperatorHub.io

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostatio.github.io#34]
The operator is now live on OperatorHub.io: https://operatorhub.io/operator/cryostat-operator. We should update the website to reflect that by replacing the section "Install with operator bundle" with "Install from OperatorHub.io".

I'm not sure if we want to keep the "Install with kubectl" option as well. If we do, I would place the OperatorHub.io option above it as our preferred method.

**Comment by jan-law** [comment]
@hareetd did you want to take this one or can I?
