### ISSUE TITLE
Add Guide for Automated Rules

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostatio.github.io#36]
We should have an upstream guide for automated rules. The content can generally be a copy or light rewrite of my downstream blog post on the same topic: https://developers.redhat.com/articles/2021/11/09/automating-jdk-flight-recorder-containers

**Comment by jan-law** [comment]
Does the automated rules UI have the ability to pass a `clean=true` parameter to the backend? It would be nice to include this last section about adjusting the event template at runtime: https://developers.redhat.com/articles/2021/11/09/automating-jdk-flight-recorder-containers#use_case_1__continuous_monitoring_in_a_containerized_jvm

**Comment by jan-law** [comment]
Also, this guide should probably be in the 2.1.0 version of the Guides page, but the latest version is 2.0.0 in the dropdown. I was thinking of making another PR to create a new 2.1.0 Guides page (copied from 2.0.0) and then rebasing the automated rules PR on top of that one to avoid publishing the content too early. What do you think?

**Comment by andrewazores** [comment]
> Also, this guide should probably be in the 2.1.0 version of the Guides page, but the latest version is 2.0.0 in the dropdown. I was thinking of making another PR to create a new 2.1.0 Guides page (copied from 2.0.0) and then rebasing the automated rules PR on top of that one to avoid publishing the content too early. What do you think?

Sounds like a good plan. The PR for adding a 2.1.0 section will be held until the upstream release of 2.1.0 is actually ready for publishing, though.

**Comment by andrewazores** [comment]
> Does the automated rules UI have the ability to pass a `clean=true` parameter to the backend? It would be nice to include this last section about adjusting the event template at runtime: https://developers.redhat.com/articles/2021/11/09/automating-jdk-flight-recorder-containers#use_case_1__continuous_monitoring_in_a_containerized_jvm

Currently no, but that feature is tracked as part of this issue: https://github.com/cryostatio/cryostat-web/issues/382
