### ISSUE TITLE
Update Getting Started for 2.1

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostatio.github.io#47]
https://cryostat.io/get-started/

OAuth login flow "Authenticating to Cryostat" section needs updating, along with screenshot(s)

**Comment by andrewazores** [comment]
@ebaron do you know if we can also update the OLM version that we instruct users to install here? We specify `v0.20.0` but there is now a `v0.21.1`.

**Comment by ebaron** [comment]
Yes I think so, OperatorHub.io now shows the following:
`curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.21.1/install.sh | bash -s v0.21.1`
