### ISSUE TITLE
[Task] All-Targets Archives view section

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostatio.github.io#56]
2.1.0's All-Targets Archives view needs documentation.

**Comment by andrewazores** [comment]
There is a rewrite for this view coming in 2.2.0 which will also need an updated version after #54.

**Comment by maxcao13** [comment]
Closed by the mentioned PRs above.

**Comment by maxcao13** [comment]
Closed by the mentioned PRs above.
